# Generated by Django 3.1.13 on 2021-11-20 05:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Animator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Animator',
            },
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_number', models.CharField(max_length=10, unique=True)),
                ('address', models.CharField(max_length=100, unique=True)),
                ('city', models.CharField(max_length=100, unique=True)),
                ('state', models.CharField(max_length=100, unique=True)),
                ('swim', models.CharField(choices=[('NO', 'No'), ('YES', 'Yes'), ('ABIT', 'a little bit')], default='NO', max_length=4)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Child',
                'verbose_name_plural': 'Children',
            },
        ),
        migrations.CreateModel(
            name='ChildGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='tabor2022', max_length=100)),
                ('registration_start', models.DateField()),
                ('registration_end', models.DateField()),
                ('camp_start_date', models.DateField()),
                ('camp_start_end', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('paid', models.BooleanField(default=False)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camper.child')),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camper.registration')),
            ],
            options={
                'verbose_name': 'Participation',
            },
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consent', models.BooleanField(default=False)),
                ('contanct_phone', models.CharField(max_length=17)),
                ('contanct_email', models.CharField(max_length=128)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Parent',
            },
        ),
        migrations.CreateModel(
            name='GroupChild',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camper.child')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camper.childgroup')),
            ],
            options={
                'verbose_name_plural': 'Group Children',
            },
        ),
        migrations.CreateModel(
            name='GroupAnimator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camper.animator')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camper.childgroup')),
            ],
        ),
        migrations.CreateModel(
            name='ChildParent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camper.child')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camper.parent')),
            ],
        ),
        migrations.CreateModel(
            name='ChildHealth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_name', models.CharField(max_length=100, unique=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camper.child')),
            ],
        ),
        migrations.AddField(
            model_name='childgroup',
            name='registration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camper.registration'),
        ),
    ]
