# Generated by Django 3.1.13 on 2021-10-30 15:37

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animator',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
                ('rc', models.CharField(max_length=10, unique=True)),
                ('address', models.CharField(max_length=100, unique=True)),
                ('city', models.CharField(max_length=100, unique=True)),
                ('state', models.CharField(max_length=100, unique=True)),
                ('swim', models.CharField(choices=[('NO', 'No'), ('YES', 'Yes'), ('ABIT', 'a little bit')], default='NO', max_length=4)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ChildGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
                ('consent', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='tabor2022', max_length=100)),
                ('registration_start', models.DateField()),
                ('registration_end', models.DateField()),
                ('camp_start_date', models.DateField()),
                ('camp_start_end', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('paid', models.BooleanField(default=False)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camper.child')),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camper.registration')),
            ],
        ),
        migrations.CreateModel(
            name='GroupChild',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camper.child')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camper.childgroup')),
            ],
        ),
        migrations.CreateModel(
            name='GroupAnimator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camper.animator')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camper.childgroup')),
            ],
        ),
        migrations.CreateModel(
            name='ChildParent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camper.child')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camper.parent')),
            ],
        ),
        migrations.CreateModel(
            name='ChildHealth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='name', max_length=100, unique=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camper.child')),
            ],
        ),
        migrations.AddField(
            model_name='childgroup',
            name='registration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camper.registration'),
        ),
    ]
