# Generated by Django 3.1.13 on 2021-10-31 13:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('camper', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animator',
            options={'verbose_name': 'Animator'},
        ),
        migrations.AlterModelOptions(
            name='child',
            options={'verbose_name': 'Child'},
        ),
        migrations.AlterModelOptions(
            name='parent',
            options={'verbose_name': 'Parent'},
        ),
        migrations.AddField(
            model_name='parent',
            name='contanct_email',
            field=models.CharField(default=django.utils.timezone.now, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parent',
            name='contanct_phone',
            field=models.CharField(default='111', max_length=17),
            preserve_default=False,
        ),
    ]
