# Generated by Django 3.1.13 on 2021-11-20 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camper', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='participant',
            options={'verbose_name': 'Participation', 'verbose_name_plural': 'Participation'},
        ),
        migrations.RenameField(
            model_name='parent',
            old_name='consent',
            new_name='consent_agreement',
        ),
        migrations.AddField(
            model_name='parent',
            name='consent_photo',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='childparent',
            unique_together={('parent', 'child')},
        ),
    ]
