# Generated by Django 3.1.13 on 2021-10-31 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camper', '0002_auto_20211031_1424'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='child',
            options={'verbose_name': 'Child', 'verbose_name_plural': 'Children'},
        ),
        migrations.AlterModelOptions(
            name='participant',
            options={'verbose_name': 'Participation'},
        ),
        migrations.RemoveField(
            model_name='childhealth',
            name='name',
        ),
        migrations.AddField(
            model_name='childhealth',
            name='disease_name',
            field=models.CharField(default='q', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
