# Generated by Django 3.1.13 on 2021-11-30 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('camper', '0002_auto_20211120_0736'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parent',
            old_name='contanct_email',
            new_name='contact_email',
        ),
        migrations.RenameField(
            model_name='parent',
            old_name='contanct_phone',
            new_name='contact_phone',
        ),
    ]
