# Generated by Django 3.1.13 on 2021-12-04 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camper', '0003_auto_20211130_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='child',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='child',
            name='state',
            field=models.CharField(max_length=100),
        ),
    ]
