# Generated by Django 3.1.13 on 2021-10-31 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('camper', '0003_auto_20211031_1431'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupchild',
            options={'verbose_name_plural': 'Group Children'},
        ),
    ]
