# Generated by Django 3.1.13 on 2021-12-04 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camper', '0004_auto_20211204_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='price',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=4),
        ),
    ]
