# Generated by Django 3.1.13 on 2021-12-04 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camper', '0005_registration_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childhealth',
            name='disease_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='childhealth',
            unique_together={('disease_name', 'child')},
        ),
    ]
