# Generated by Django 3.1.13 on 2021-12-31 01:14

import camper.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camper', '0006_auto_20211204_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='advance_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='participant',
            name='advance_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='participant',
            name='qr_advance',
            field=models.CharField(blank=True, max_length=1000000, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='qr_diff',
            field=models.CharField(blank=True, max_length=1000000, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='valid_participant',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='advance_price',
            field=models.DecimalField(decimal_places=2, default=3, max_digits=4),
        ),
        migrations.AddField(
            model_name='registration',
            name='bank_account',
            field=models.CharField(default='SK31 8330 0000 0024 0188 0167', max_length=100),
        ),
        migrations.AlterField(
            model_name='child',
            name='birth_number',
            field=models.CharField(max_length=10, unique=True, validators=[camper.models.validate_rc]),
        ),
    ]
