# Generated by Django 3.1.14 on 2022-03-24 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camper', '0007_auto_20211231_0214'),
    ]

    operations = [
        migrations.AddField(
            model_name='animator',
            name='animation_img',
            field=models.FileField(blank=True, null=True, upload_to='animators'),
        ),
        migrations.AddField(
            model_name='animator',
            name='description',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='animator',
            name='label',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='animator',
            name='main_img',
            field=models.FileField(blank=True, null=True, upload_to='animators'),
        ),
        migrations.AddField(
            model_name='animator',
            name='registrations',
            field=models.ManyToManyField(blank=True, to='camper.Registration'),
        ),
    ]
