# Generated by Django 3.1.14 on 2022-03-26 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camper', '0008_auto_20220324_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='advance_price',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='participant',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
