# Generated by Django 3.1.14 on 2022-03-28 23:24

import camper.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camper', '0011_animator_general_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='date_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='child',
            name='birth_number',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[camper.models.validate_rc]),
        ),
    ]
