# Generated by Django 3.1.14 on 2022-03-29 21:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('camper', '0012_auto_20220329_0124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='date_birth',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
