# Generated by Django 3.1.14 on 2022-03-29 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camper', '0013_auto_20220329_2352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parent',
            name='consent_agreement',
        ),
        migrations.RemoveField(
            model_name='parent',
            name='consent_photo',
        ),
        migrations.AddField(
            model_name='participant',
            name='consent_agreement',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='participant',
            name='consent_photo',
            field=models.BooleanField(default=False),
        ),
    ]
