# Generated by Django 3.1.14 on 2022-06-15 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('camper', '0015_auto_20220330_0150'),
    ]

    operations = [
        migrations.AddField(
            model_name='animator',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='animator',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='animator',
            name='consent_of_parent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='animator',
            name='consent_photo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='animator',
            name='date_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='animator',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='AnimatorHealth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_name', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('animator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camper.animator')),
            ],
            options={
                'unique_together': {('disease_name', 'animator')},
            },
        ),
    ]
